/**
 * SIGEIT-API Documentation
 * API completa para el Sistema de Gestión de Información Educativa y Tecnológica
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IdCreateEntity } from './id-create-entity';


export interface CreateUserDto { 
    email: string;
    role: string;
    idDocument: string;
    name: string;
    lastName?: string;
    firstName?: string;
    teacher: IdCreateEntity;
    status: boolean;
    school: IdCreateEntity;
    department: IdCreateEntity;
    career: IdCreateEntity;
}

