export * from './auth.service';
import { AuthApiService } from './auth.service';
export * from './career.service';
import { CareerApiService } from './career.service';
export * from './classroom.service';
import { ClassroomApiService } from './classroom.service';
export * from './day.service';
import { DayApiService } from './day.service';
export * from './default.service';
import { DefaultApiService } from './default.service';
export * from './department.service';
import { DepartmentApiService } from './department.service';
export * from './document.service';
import { DocumentApiService } from './document.service';
export * from './inscription.service';
import { InscriptionApiService } from './inscription.service';
export * from './period.service';
import { PeriodApiService } from './period.service';
export * from './schedule.service';
import { ScheduleApiService } from './schedule.service';
export * from './school.service';
import { SchoolApiService } from './school.service';
export * from './section.service';
import { SectionApiService } from './section.service';
export * from './subject.service';
import { SubjectApiService } from './subject.service';
export * from './teacher.service';
import { TeacherApiService } from './teacher.service';
export * from './user.service';
import { UserApiService } from './user.service';
export const APIS = [AuthApiService, CareerApiService, ClassroomApiService, DayApiService, DefaultApiService, DepartmentApiService, DocumentApiService, InscriptionApiService, PeriodApiService, ScheduleApiService, SchoolApiService, SectionApiService, SubjectApiService, TeacherApiService, UserApiService];
