/**
 * SIGEIT-API Documentation
 * API completa para el Sistema de Gestión de Información Educativa y Tecnológica
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResponseDepartmentDto { 
    id: number;
    name: string;
    description?: string;
    logo?: string;
    abbreviation: string;
    schoolId: number;
    school: object;
    status: boolean;
}

