/**
 * SIGEIT-API Documentation
 * API completa para el Sistema de Gestión de Información Educativa y Tecnológica
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResponseTeacherDto { 
    id: number;
    idDocument: string;
    firstName: string;
    lastName?: string;
    email?: string;
    departmentId: number;
    department: object;
    status: boolean;
}

