/**
 * SIGEIT-API Documentation
 * API completa para el Sistema de Gestión de Información Educativa y Tecnológica
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserRespondeDto { 
    id: number;
    name: string;
    lastName: string;
    firstName: string;
    email: string;
    role: string;
    idDocument: string;
    status: boolean;
    teacherId: number;
    teacher: object;
    schoolId: number;
    school: object;
    departmentId: number;
    department: object;
    careerId: number;
    career: object;
}

