/**
 * SIGEIT-API
 * The SIGEIT-APIdescription
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface CreateScheduleDto { 
    start: string;
    end: string;
    classroomId: number;
    dayId: number;
    sectionId: number;
    periodId: number;
    status: boolean;
}