/**
 * SIGEIT-API
 * The SIGEIT-APIdescription
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { School } from './school';

export interface CreateDepartmentDto { 
    name: string;
    description?: string;
    logo?: string;
    abbreviation: string;
    school: School;
    status: boolean;
}