/**
 * SIGEIT-API
 * The SIGEIT-APIdescription
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { IdCreateEntity } from './idCreateEntity';

export interface CreateUserDto { 
    email: string;
    role: CreateUserDto.RoleEnum;
    idDocument: string;
    name: string;
    lastName?: string;
    firstName?: string;
    teacher?: IdCreateEntity;
    status: boolean;
    school?: IdCreateEntity;
    department?: IdCreateEntity;
    career?: IdCreateEntity;
    id?: number;
}
export namespace CreateUserDto {
    export type RoleEnum = 'admin' | 'director' | 'head-department' | 'planner' | 'teacher' | 'student';
    export const RoleEnum = {
        Admin: 'admin' as RoleEnum,
        Director: 'director' as RoleEnum,
        HeadDepartment: 'head-department' as RoleEnum,
        Planner: 'planner' as RoleEnum,
        Teacher: 'teacher' as RoleEnum,
        Student: 'student' as RoleEnum
    };
}