/**
 * SIGEIT-API
 * The SIGEIT-APIdescription
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Classroom } from './classroom';
import { IdCreateEntity } from './idCreateEntity';

export interface CreateDepartmentDto { 
    name: string;
    description?: string;
    logo?: string;
    abbreviation: string;
    school: IdCreateEntity;
    status: boolean;
    id?: number;
    classrooms?: Array<Classroom>;
}