/**
 * SIGEIT-API Documentation
 * API completa para el Sistema de Gestión de Información Educativa y Tecnológica. Módulo **statistics** (`/statistics/_*`): métricas en camelCase para dashboards (comparación de períodos, docentes por día, carga, aulas, etc.); no usa datos de inscripciones.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TeacherCategory } from './teacher-category';
import { IdCreateEntity } from './id-create-entity';
import { HiringEvaluationStatus } from './hiring-evaluation-status';
import { TeacherDedication } from './teacher-dedication';
import { EmploymentStatus } from './employment-status';


export interface CreateTeacherDto { 
    idDocument: string;
    firstName: string;
    lastName?: string;
    email?: string;
    department: IdCreateEntity;
    status: boolean;
    category?: TeacherCategory;
    employmentStatus?: EmploymentStatus;
    dedication?: TeacherDedication;
    hiringEvaluationStatus?: HiringEvaluationStatus;
    hiringEvaluationDate?: string | null;
    hiringEvaluationNotes?: string | null;
}
export namespace CreateTeacherDto {
}


