/**
 * SIGEIT-API Documentation
 * API completa para el Sistema de Gestión de Información Educativa y Tecnológica
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GenerateReportDto { 
    /**
     * ID del período académico
     */
    periodId: number;
    /**
     * ID del departamento
     */
    departmentId: number;
    /**
     * Campo por el cual agrupar (semester o teacherName)
     */
    groupBy?: string;
    /**
     * ID del semestre específico
     */
    semester?: number;
    /**
     * ID del profesor específico
     */
    teacherId?: number;
    /**
     * Estado de las secciones
     */
    status?: boolean;
}

