/**
 * SIGEIT-API Documentation
 * API completa para el Sistema de Gestión de Información Educativa y Tecnológica. Módulo **statistics** (`/statistics/_*`): métricas en camelCase para dashboards (comparación de períodos, docentes por día, carga, aulas, etc.); no usa datos de inscripciones.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Deducido de la nota (según la mínima aprobatoria) o del resultado
 */
export type GradeStatus = 'APPROVED' | 'FAILED' | 'WITHDRAWN' | 'IN_PROGRESS';

export const GradeStatus = {
    Approved: 'APPROVED' as GradeStatus,
    Failed: 'FAILED' as GradeStatus,
    Withdrawn: 'WITHDRAWN' as GradeStatus,
    InProgress: 'IN_PROGRESS' as GradeStatus
};

