/**
 * SIGEIT-API
 * The SIGEIT-APIdescription
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Section } from './section';
import { User } from './user';

export interface Inscription { 
    stage: string;
    section: Section;
    user: User;
    id: number;
    createdAt: Date;
    updatedAt: Date;
    status?: boolean;
    deleted?: boolean;
}