/**
 * SIGEIT-API
 * The SIGEIT-APIdescription
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Department } from './department';
import { School } from './school';
import { Teacher } from './teacher';

export interface LoginUserResponseDto { 
    email: string;
    id: number;
    name: string;
    role: string;
    loginStamp: number;
    school: School;
    department: Department;
    teacher: Teacher;
}