/**
 * SIGEIT-API Documentation
 * API completa para el Sistema de Gestión de Información Educativa y Tecnológica. Módulo **statistics** (`/statistics/_*`): métricas en camelCase para dashboards (comparación de períodos, docentes por día, carga, aulas, etc.); no usa datos de inscripciones.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PeriodMetricResponseDto { 
    periodId: number;
    periodName: string;
    /**
     * Fecha de inicio del período (ISO).
     */
    periodStart: string;
    sectionCount: number;
    /**
     * Suma de capacidades de las secciones.
     */
    totalCapacity: number;
    /**
     * Suma de horas de materia por sección (carga académica ofertada).
     */
    totalSubjectHours: number;
}

