/**
 * SIGEIT-API Documentation
 * API completa para el Sistema de Gestión de Información Educativa y Tecnológica. Módulo **statistics** (`/statistics/_*`): métricas en camelCase para dashboards (comparación de períodos, docentes por día, carga, aulas, etc.); no usa datos de inscripciones.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SubjectDemandIncreaseItemDto } from './subject-demand-increase-item-dto';
import { PeriodMetricResponseDto } from './period-metric-response-dto';
import { PeriodComparisonDeltaDto } from './period-comparison-delta-dto';


export interface PeriodComparisonResponseDto { 
    metrics: Array<PeriodMetricResponseDto>;
    /**
     * El primer elemento corresponde al primer periodId enviado (deltas en 0).
     */
    deltasFromFirst: Array<PeriodComparisonDeltaDto>;
    /**
     * Asignaturas cuyo cupo o número de secciones aumentó entre el primer y el último período comparado.
     */
    subjectDemandIncreases: Array<SubjectDemandIncreaseItemDto>;
}

