/**
 * SIGEIT-API Documentation
 * API completa para el Sistema de Gestión de Información Educativa y Tecnológica. Módulo **statistics** (`/statistics/_*`): métricas en camelCase para dashboards (comparación de períodos, docentes por día, carga, aulas, etc.); no usa datos de inscripciones.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AuditSummaryDto } from './audit-summary-dto';
import { ScheduleLiteDto } from './schedule-lite-dto';
import { ConflictPairDto } from './conflict-pair-dto';
import { SectionCoverageDto } from './section-coverage-dto';


export interface PeriodAuditDto { 
    summary: AuditSummaryDto;
    /**
     * Aula física ocupada dos veces
     */
    classroom: Array<ConflictPairDto>;
    /**
     * Mismo profesor en dos bloques a la vez
     */
    teacher: Array<ConflictPairDto>;
    /**
     * Asignaturas del mismo nivel pico a la vez
     */
    level: Array<ConflictPairDto>;
    /**
     * Bloques fuera de la franja del período o con horas inválidas
     */
    outOfRange: Array<ScheduleLiteDto>;
    /**
     * Secciones sin horas completas (vacías, incompletas o excedidas)
     */
    incompleteSections: Array<SectionCoverageDto>;
}

