/**
 * SIGEIT-API Documentation
 * API completa para el Sistema de Gestión de Información Educativa y Tecnológica. Módulo **statistics** (`/statistics/_*`): métricas en camelCase para dashboards (comparación de períodos, docentes por día, carga, aulas, etc.); no usa datos de inscripciones.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResponseAuditLogDto { 
    id: number;
    userId?: string;
    userEmail?: string;
    action: ResponseAuditLogDto.ActionEnum;
    resource: string;
    resourceId?: string;
    httpMethod: string;
    path: string;
    ipAddress?: string;
    /**
     * User-Agent enviado por el navegador (truncado)
     */
    userAgent?: string;
    /**
     * Resumen navegador/SO derivado del User-Agent
     */
    clientSummary?: string;
    payloadSnippet?: string;
    /**
     * En updates: mapa campo → { previous, current }. En CREATE: fieldsSubmitted.
     */
    propertyChanges?: { [key: string]: any; };
    statusCode: number;
    success: boolean;
    createdAt: string;
}
export namespace ResponseAuditLogDto {
    export type ActionEnum = 'CREATE' | 'UPDATE' | 'DELETE' | 'OTHER' | 'AUTH_LOGIN' | 'AUTH_LOGOUT' | 'AUTH_RECOVERY_REQUEST' | 'AUTH_RECOVERY_VALIDATE' | 'AUTH_RECOVERY_COMPLETE' | 'AUTH_CHANGE_PASSWORD' | 'AUTH_REGISTER_PUBLIC' | 'AUTH_OTHER';
    export const ActionEnum = {
        Create: 'CREATE' as ActionEnum,
        Update: 'UPDATE' as ActionEnum,
        Delete: 'DELETE' as ActionEnum,
        Other: 'OTHER' as ActionEnum,
        AuthLogin: 'AUTH_LOGIN' as ActionEnum,
        AuthLogout: 'AUTH_LOGOUT' as ActionEnum,
        AuthRecoveryRequest: 'AUTH_RECOVERY_REQUEST' as ActionEnum,
        AuthRecoveryValidate: 'AUTH_RECOVERY_VALIDATE' as ActionEnum,
        AuthRecoveryComplete: 'AUTH_RECOVERY_COMPLETE' as ActionEnum,
        AuthChangePassword: 'AUTH_CHANGE_PASSWORD' as ActionEnum,
        AuthRegisterPublic: 'AUTH_REGISTER_PUBLIC' as ActionEnum,
        AuthOther: 'AUTH_OTHER' as ActionEnum
    };
}


