/**
 * SIGEIT-API Documentation
 * API completa para el Sistema de Gestión de Información Educativa y Tecnológica
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResponseSectionDto { 
    id: number;
    capacity: number;
    inscribed: number;
    name: string;
    subjectId: number;
    subject: object;
    periodId: number;
    period: object;
    teacherId: number;
    teacher: object;
    status: boolean;
    all: boolean;
}

