/**
 * SIGEIT-API
 * The SIGEIT-APIdescription
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Section } from './section';
import { User } from './user';

export interface ResponseInscriptionDto { 
    id: number;
    stage: ResponseInscriptionDto.StageEnum;
    sectionId: number;
    section: Section;
    userId: number;
    user: User;
}
export namespace ResponseInscriptionDto {
    export type StageEnum = 'Validated' | 'Registered';
    export const StageEnum = {
        Validated: 'Validated' as StageEnum,
        Registered: 'Registered' as StageEnum
    };
}