/**
 * SIGEIT-API
 * The SIGEIT-APIdescription
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Department } from './department';

export interface ResponseDocumentDto { 
    id: number;
    name: string;
    description: string;
    type: ResponseDocumentDto.TypeEnum;
    departmentId: number;
    department: Department;
    status: boolean;
}
export namespace ResponseDocumentDto {
    export type TypeEnum = 'academic_charge';
    export const TypeEnum = {
        AcademicCharge: 'academic_charge' as TypeEnum
    };
}