/**
 * SIGEIT-API
 * The SIGEIT-APIdescription
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Department } from './department';

export interface ResponseClassroomDto { 
    id: number;
    name: string;
    description?: string;
    type: string;
    departamentIds: Array<number>;
    departaments: Array<Department>;
    status: boolean;
}