/**
 * SIGEIT-API Documentation
 * API completa para el Sistema de Gestión de Información Educativa y Tecnológica. Módulo **statistics** (`/statistics/_*`): métricas en camelCase para dashboards (comparación de períodos, docentes por día, carga, aulas, etc.); no usa datos de inscripciones.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SubjectDemandIncreaseItemDto { 
    subjectId: number;
    subjectCode: string;
    subjectName: string;
    /**
     * Capacidad total en el período base.
     */
    baseTotalCapacity: number;
    /**
     * Capacidad total en el período de referencia (último de la comparación).
     */
    referenceTotalCapacity: number;
    /**
     * Diferencia de capacidad entre el período de referencia y el base.
     */
    capacityDelta: number;
    /**
     * Cantidad de secciones en el período base.
     */
    baseSectionCount: number;
    /**
     * Cantidad de secciones en el período de referencia.
     */
    referenceSectionCount: number;
    /**
     * Diferencia de secciones entre el período de referencia y el base.
     */
    sectionDelta: number;
}

