/**
 * SIGEIT-API Documentation
 * API completa para el Sistema de Gestión de Información Educativa y Tecnológica. Módulo **statistics** (`/statistics/_*`): métricas en camelCase para dashboards (comparación de períodos, docentes por día, carga, aulas, etc.); no usa datos de inscripciones.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TeacherDegreePeriodDto { 
    /**
     * Código del período
     */
    code: string;
    /**
     * Fechas o descripción del período
     */
    label?: string;
    /**
     * Promedio del período
     */
    average?: number;
    /**
     * Créditos aprobados en el período
     */
    approvedCredits?: number;
}

