/**
 * SIGEIT-API Documentation
 * API completa para el Sistema de Gestión de Información Educativa y Tecnológica. Módulo **statistics** (`/statistics/_*`): métricas en camelCase para dashboards (comparación de períodos, docentes por día, carga, aulas, etc.); no usa datos de inscripciones.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TeacherDegreeSummaryDto { 
    /**
     * Períodos académicos cursados
     */
    periods: number;
    /**
     * Asignaturas distintas cursadas
     */
    subjects: number;
    /**
     * Notas aprobadas (incluye equivalencias)
     */
    approved: number;
    failed: number;
    withdrawn: number;
    inProgress: number;
    /**
     * Asignaturas cursadas más de una vez
     */
    repeated: number;
    /**
     * Notas con asignatura equivalente del pensum
     */
    equivalences: number;
    /**
     * Promedio simple de las notas numéricas (sin retiros); el oficial está en `average`
     */
    gradeAverage?: number;
}

