/**
 * SIGEIT-API Documentation
 * API completa para el Sistema de Gestión de Información Educativa y Tecnológica. Módulo **statistics** (`/statistics/_*`): métricas en camelCase para dashboards (comparación de períodos, docentes por día, carga, aulas, etc.); no usa datos de inscripciones.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SubjectRefDto } from './subject-ref-dto';


export interface TeacherGradeDto { 
    code?: string;
    subjectName: string;
    period?: string;
    /**
     * Nota numérica en la escala del título (maxGrade)
     */
    grade?: number;
    /**
     * Resultado no numérico (RETIRADA, APROBADO, EN EJECUCIÓN)
     */
    remark?: string;
    subject?: SubjectRefDto;
}

