/**
 * SIGEIT-API Documentation
 * API completa para el Sistema de Gestión de Información Educativa y Tecnológica. Módulo **statistics** (`/statistics/_*`): métricas en camelCase para dashboards (comparación de períodos, docentes por día, carga, aulas, etc.); no usa datos de inscripciones.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TeacherGradeDto } from './teacher-grade-dto';


export interface TranscriptPreviewDto { 
    /**
     * Cédula del estudiante, solo dígitos
     */
    idDocument?: string;
    studentName?: string;
    /**
     * Carrera o programa
     */
    title?: string;
    institution?: string;
    /**
     * Nota máxima de la escala: la del documento, o 10/20 según las notas si no la indica
     */
    maxGrade: number;
    grades: Array<TeacherGradeDto>;
}

