/**
 * SIGEIT-API Documentation
 * API completa para el Sistema de Gestión de Información Educativa y Tecnológica. Módulo **statistics** (`/statistics/_*`): métricas en camelCase para dashboards (comparación de períodos, docentes por día, carga, aulas, etc.); no usa datos de inscripciones.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdatePeriodDto { 
    name?: string;
    description?: string;
    start?: string;
    end?: string;
    startTime?: string;
    endTime?: string;
    stage?: string;
    interval?: number;
    duration?: number;
    copyPrevious?: boolean;
    status?: boolean;
    /**
     * Marcar como período activo (solo uno puede estarlo)
     */
    isActive?: boolean;
    /**
     * Indica si el período académico es un curso vacacional
     */
    isVacationCourse?: boolean;
}

