/**
 * SM-SOC
 * The SM-SOC API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UpdatePublicationDto { 
    socialNetworkId?: number;
    socialProgramId?: number;
    description?: string;
    date?: Date;
    type?: string;
    likes?: number;
    shared?: number;
    comments?: number;
    usersReached?: number;
    link?: string;
}