/**
 * SIGEIT-API
 * The SIGEIT-APIdescription
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UpdatePeriodDto { 
    name?: string;
    description?: string;
    start?: Date;
    end?: Date;
    startTime?: string;
    endTime?: string;
    stage?: UpdatePeriodDto.StageEnum;
    interval?: number;
    duration?: number;
    status?: boolean;
    id?: number;
}
export namespace UpdatePeriodDto {
    export type StageEnum = 'Por Planificar' | 'Finalizado';
    export const StageEnum = {
        PorPlanificar: 'Por Planificar' as StageEnum,
        Finalizado: 'Finalizado' as StageEnum
    };
}