/**
 * SIGEIT-API
 * The SIGEIT-APIdescription
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { IdCreateEntity } from './idCreateEntity';
import { Subject } from './subject';

export interface UpdateTeacherDto { 
    idDocument?: string;
    firstName?: string;
    lastName?: string;
    email?: string;
    department?: IdCreateEntity;
    status?: boolean;
    id?: number;
    name?: string;
    description?: string;
    logo?: string;
    abbreviation?: string;
    subjects?: Array<Subject>;
}