/**
 * SIGEIT-API
 * The SIGEIT-APIdescription
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { IdCreateEntity } from './idCreateEntity';

export interface UpdateSubjectDto { 
    name?: string;
    code?: string;
    credits?: number;
    description?: string;
    hours?: number;
    semester?: number;
    typeCurriculum?: number;
    department?: IdCreateEntity;
    careers?: Array<IdCreateEntity>;
    id?: number;
    status?: boolean;
}