/**
 * SIGEIT-API
 * The SIGEIT-APIdescription
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { IdCreateEntity } from './idCreateEntity';

export interface UpdateUserDto { 
    email?: string;
    role?: UpdateUserDto.RoleEnum;
    idDocument?: string;
    teacher?: IdCreateEntity;
    status?: boolean;
    school?: IdCreateEntity;
    department?: IdCreateEntity;
    id?: number;
    name?: string;
}
export namespace UpdateUserDto {
    export type RoleEnum = 'admin' | 'director' | 'head-department' | 'planner' | 'teacher';
    export const RoleEnum = {
        Admin: 'admin' as RoleEnum,
        Director: 'director' as RoleEnum,
        HeadDepartment: 'head-department' as RoleEnum,
        Planner: 'planner' as RoleEnum,
        Teacher: 'teacher' as RoleEnum
    };
}