/**
 * SIGEIT-API
 * The SIGEIT-APIdescription
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UpdatePeriodDto { 
    name?: string;
    description?: string;
    start?: Date;
    end?: Date;
    startTime?: string;
    endTime?: string;
    stage?: UpdatePeriodDto.StageEnum;
    interval?: number;
    duration?: number;
    copyPrevious?: boolean;
    status?: boolean;
    id?: number;
}
export namespace UpdatePeriodDto {
    export type StageEnum = 'TO_START' | 'TO_PLAN' | 'PLANNED' | 'FINALIZED';
    export const StageEnum = {
        TOSTART: 'TO_START' as StageEnum,
        TOPLAN: 'TO_PLAN' as StageEnum,
        PLANNED: 'PLANNED' as StageEnum,
        FINALIZED: 'FINALIZED' as StageEnum
    };
}