/**
 * SIGEIT-API
 * The SIGEIT-APIdescription
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { IdCreateEntity } from './idCreateEntity';

export interface UpdateInscriptionDto { 
    stage?: UpdateInscriptionDto.StageEnum;
    section?: IdCreateEntity;
    user?: IdCreateEntity;
    id?: number;
    status?: boolean;
}
export namespace UpdateInscriptionDto {
    export type StageEnum = 'Validated' | 'Registered';
    export const StageEnum = {
        Validated: 'Validated' as StageEnum,
        Registered: 'Registered' as StageEnum
    };
}