/**
 * SIGEIT-API
 * The SIGEIT-APIdescription
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { IdCreateEntity } from './idCreateEntity';

export interface UpdateDocumentDto { 
    name?: string;
    description?: string;
    type?: UpdateDocumentDto.TypeEnum;
    department?: IdCreateEntity;
    id?: number;
    status?: boolean;
}
export namespace UpdateDocumentDto {
    export type TypeEnum = 'academic_charge';
    export const TypeEnum = {
        AcademicCharge: 'academic_charge' as TypeEnum
    };
}