/**
 * SIGEIT-API
 * The SIGEIT-APIdescription
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Department } from './department';
import { School } from './school';
import { Teacher } from './teacher';

export interface UserRespondeDto { 
    id: number;
    name: string;
    email: string;
    role: string;
    idDocument: string;
    status: boolean;
    teacherId: number;
    teacher: Teacher;
    schoolId: number;
    school: School;
    departmentId: number;
    department: Department;
}