/**
 * SIGEIT-API
 * The SIGEIT-APIdescription
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Career } from './career';
import { Department } from './department';
import { School } from './school';
import { Teacher } from './teacher';

export interface User { 
    name: string;
    firstName: string;
    lastName: string;
    email: string;
    idDocument: string;
    role: string;
    teacher?: Teacher;
    school?: School;
    department?: Department;
    career?: Career;
    id: number;
    createdAt: Date;
    updatedAt: Date;
    status?: boolean;
    deleted?: boolean;
}