/**
 * SM-SOC
 * The SM-SOC API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { ChangePasswordDto } from '../model/changePasswordDto';
import { ChangePasswordResponseDto } from '../model/changePasswordResponseDto';
import { LoginDto } from '../model/loginDto';
import { LoginUserResponseDto } from '../model/loginUserResponseDto';
import { RecoveryPasswordDto } from '../model/recoveryPasswordDto';
import { RecoveryPasswordResponseDto } from '../model/recoveryPasswordResponseDto';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class AuthService {

    protected basePath = '/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public authControllerChangePassword(body: ChangePasswordDto, observe?: 'body', reportProgress?: boolean): Observable<ChangePasswordResponseDto>;
    public authControllerChangePassword(body: ChangePasswordDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ChangePasswordResponseDto>>;
    public authControllerChangePassword(body: ChangePasswordDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ChangePasswordResponseDto>>;
    public authControllerChangePassword(body: ChangePasswordDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling authControllerChangePassword.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<ChangePasswordResponseDto>('put',`${this.basePath}/auth/change-password`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public authControllerGenerateRecovery(body: RecoveryPasswordDto, observe?: 'body', reportProgress?: boolean): Observable<RecoveryPasswordDto>;
    public authControllerGenerateRecovery(body: RecoveryPasswordDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<RecoveryPasswordDto>>;
    public authControllerGenerateRecovery(body: RecoveryPasswordDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<RecoveryPasswordDto>>;
    public authControllerGenerateRecovery(body: RecoveryPasswordDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling authControllerGenerateRecovery.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<RecoveryPasswordDto>('post',`${this.basePath}/auth/recovery-password`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param recoveryToken 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public authControllerGetRecoveryById(recoveryToken: string, observe?: 'body', reportProgress?: boolean): Observable<RecoveryPasswordResponseDto>;
    public authControllerGetRecoveryById(recoveryToken: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<RecoveryPasswordResponseDto>>;
    public authControllerGetRecoveryById(recoveryToken: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<RecoveryPasswordResponseDto>>;
    public authControllerGetRecoveryById(recoveryToken: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (recoveryToken === null || recoveryToken === undefined) {
            throw new Error('Required parameter recoveryToken was null or undefined when calling authControllerGetRecoveryById.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<RecoveryPasswordResponseDto>('get',`${this.basePath}/auth/recovery-password/${encodeURIComponent(String(recoveryToken))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public authControllerLogin(body: LoginDto, observe?: 'body', reportProgress?: boolean): Observable<LoginUserResponseDto>;
    public authControllerLogin(body: LoginDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<LoginUserResponseDto>>;
    public authControllerLogin(body: LoginDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<LoginUserResponseDto>>;
    public authControllerLogin(body: LoginDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling authControllerLogin.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<LoginUserResponseDto>('post',`${this.basePath}/auth/login`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public authControllerLogout(observe?: 'body', reportProgress?: boolean): Observable<any>;
    public authControllerLogout(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public authControllerLogout(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public authControllerLogout(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('get',`${this.basePath}/auth/logout`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param body 
     * @param recoveryToken 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public authControllerPostRecoveryById(body: ChangePasswordDto, recoveryToken: string, observe?: 'body', reportProgress?: boolean): Observable<RecoveryPasswordResponseDto>;
    public authControllerPostRecoveryById(body: ChangePasswordDto, recoveryToken: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<RecoveryPasswordResponseDto>>;
    public authControllerPostRecoveryById(body: ChangePasswordDto, recoveryToken: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<RecoveryPasswordResponseDto>>;
    public authControllerPostRecoveryById(body: ChangePasswordDto, recoveryToken: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling authControllerPostRecoveryById.');
        }

        if (recoveryToken === null || recoveryToken === undefined) {
            throw new Error('Required parameter recoveryToken was null or undefined when calling authControllerPostRecoveryById.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<RecoveryPasswordResponseDto>('post',`${this.basePath}/auth/recovery-password/${encodeURIComponent(String(recoveryToken))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
