/**
 * SIGEIT-API
 * The SIGEIT-APIdescription
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { CloseInscriptionDto } from '../model/closeInscriptionDto';
import { CreateInscriptionDto } from '../model/createInscriptionDto';
import { Inscription } from '../model/inscription';
import { ResponseInscriptionDto } from '../model/responseInscriptionDto';
import { UpdateInscriptionDto } from '../model/updateInscriptionDto';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class InscriptionService {

    protected basePath = '/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public inscriptionControllerClose(body: CloseInscriptionDto, observe?: 'body', reportProgress?: boolean): Observable<Array<any>>;
    public inscriptionControllerClose(body: CloseInscriptionDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<any>>>;
    public inscriptionControllerClose(body: CloseInscriptionDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<any>>>;
    public inscriptionControllerClose(body: CloseInscriptionDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling inscriptionControllerClose.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<Array<any>>('post',`${this.basePath}/inscription/close`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public inscriptionControllerCreate(body: CreateInscriptionDto, observe?: 'body', reportProgress?: boolean): Observable<ResponseInscriptionDto>;
    public inscriptionControllerCreate(body: CreateInscriptionDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResponseInscriptionDto>>;
    public inscriptionControllerCreate(body: CreateInscriptionDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResponseInscriptionDto>>;
    public inscriptionControllerCreate(body: CreateInscriptionDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling inscriptionControllerCreate.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<ResponseInscriptionDto>('post',`${this.basePath}/inscription`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param id 
     * @param stage 
     * @param sectionId 
     * @param careerId 
     * @param schoolId 
     * @param departmentId 
     * @param teacherId 
     * @param subjectId 
     * @param userId 
     * @param semester 
     * @param status 
     * @param schedules 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public inscriptionControllerFindAll(id: number, stage?: string, sectionId?: number, careerId?: number, schoolId?: number, departmentId?: number, teacherId?: number, subjectId?: number, userId?: number, semester?: number, status?: boolean, schedules?: boolean, observe?: 'body', reportProgress?: boolean): Observable<Array<Inscription>>;
    public inscriptionControllerFindAll(id: number, stage?: string, sectionId?: number, careerId?: number, schoolId?: number, departmentId?: number, teacherId?: number, subjectId?: number, userId?: number, semester?: number, status?: boolean, schedules?: boolean, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Inscription>>>;
    public inscriptionControllerFindAll(id: number, stage?: string, sectionId?: number, careerId?: number, schoolId?: number, departmentId?: number, teacherId?: number, subjectId?: number, userId?: number, semester?: number, status?: boolean, schedules?: boolean, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Inscription>>>;
    public inscriptionControllerFindAll(id: number, stage?: string, sectionId?: number, careerId?: number, schoolId?: number, departmentId?: number, teacherId?: number, subjectId?: number, userId?: number, semester?: number, status?: boolean, schedules?: boolean, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling inscriptionControllerFindAll.');
        }












        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (stage !== undefined && stage !== null) {
            queryParameters = queryParameters.set('stage', <any>stage);
        }
        if (sectionId !== undefined && sectionId !== null) {
            queryParameters = queryParameters.set('sectionId', <any>sectionId);
        }
        if (careerId !== undefined && careerId !== null) {
            queryParameters = queryParameters.set('careerId', <any>careerId);
        }
        if (schoolId !== undefined && schoolId !== null) {
            queryParameters = queryParameters.set('schoolId', <any>schoolId);
        }
        if (departmentId !== undefined && departmentId !== null) {
            queryParameters = queryParameters.set('departmentId', <any>departmentId);
        }
        if (teacherId !== undefined && teacherId !== null) {
            queryParameters = queryParameters.set('teacherId', <any>teacherId);
        }
        if (subjectId !== undefined && subjectId !== null) {
            queryParameters = queryParameters.set('subjectId', <any>subjectId);
        }
        if (userId !== undefined && userId !== null) {
            queryParameters = queryParameters.set('userId', <any>userId);
        }
        if (semester !== undefined && semester !== null) {
            queryParameters = queryParameters.set('semester', <any>semester);
        }
        if (status !== undefined && status !== null) {
            queryParameters = queryParameters.set('status', <any>status);
        }
        if (schedules !== undefined && schedules !== null) {
            queryParameters = queryParameters.set('schedules', <any>schedules);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<Inscription>>('get',`${this.basePath}/inscription/period/${encodeURIComponent(String(id))}`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public inscriptionControllerFindOne(id: number, observe?: 'body', reportProgress?: boolean): Observable<ResponseInscriptionDto>;
    public inscriptionControllerFindOne(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResponseInscriptionDto>>;
    public inscriptionControllerFindOne(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResponseInscriptionDto>>;
    public inscriptionControllerFindOne(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling inscriptionControllerFindOne.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<ResponseInscriptionDto>('get',`${this.basePath}/inscription/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public inscriptionControllerRemove(id: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public inscriptionControllerRemove(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public inscriptionControllerRemove(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public inscriptionControllerRemove(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling inscriptionControllerRemove.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('delete',`${this.basePath}/inscription/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param body 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public inscriptionControllerUpdate(body: UpdateInscriptionDto, id: number, observe?: 'body', reportProgress?: boolean): Observable<ResponseInscriptionDto>;
    public inscriptionControllerUpdate(body: UpdateInscriptionDto, id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResponseInscriptionDto>>;
    public inscriptionControllerUpdate(body: UpdateInscriptionDto, id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResponseInscriptionDto>>;
    public inscriptionControllerUpdate(body: UpdateInscriptionDto, id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling inscriptionControllerUpdate.');
        }

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling inscriptionControllerUpdate.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<ResponseInscriptionDto>('patch',`${this.basePath}/inscription/${encodeURIComponent(String(id))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
